language: python
sudo: false
branches:
  only:
    - master
python:
  - 3.5
  - 3.6
  - "pypy3"
install:
  - pip install coveralls
env:
  global:
    - COVERALLS_PARALLEL=true
script:
  - coverage run setup.py test
after_success:
  - coveralls
notifications:
  webhooks: https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN
